### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by evaline-ju** [caikit/caikit-tgis-backend#33]
The tgis backend only holds a single grpc channel, so it'll create a connection to a single tgis pod and route all requests there.

We can instead:
- Create a new channel on every request (extra slow) or
- Do service-side load balancing (I'm assuming not an option / harder to change that...) or
- Do client-side load balancing with a connection pool

**Comment by desimonemike123** [comment]
Thx for inputting this issue :-)
I agree, I think best approach is "client-side load balancing with a connection pool", therefore establishing a connection to each Pod in a models replica set, and bouncing req's  between them.
Please contact me when there's a build to test out, thx (desimone@us.ibm.com)
